spring:
  application:
    name: finance-api

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/finance}
    username: ${DB_USER:finance_app}
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  flyway:
    enabled: true
    locations: classpath:db/migration

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USER}          # seu Gmail
    password: ${MAIL_PASS}          # senha de app (16 chars, sem espaços)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.connectiontimeout: 5000
      mail.smtp.timeout: 5000
      mail.smtp.writetimeout: 5000
    default-encoding: UTF-8

   

server:
  port: 8080

logging:
  level:
    root: INFO
    com.finance.api: DEBUG

security:
  jwt:
    issuer: finance-api
    access:
      ttl: 900
    refresh:
      ttl: 2592000
    secret: "Jp9y8i7Y9p4JrBzqY7B1YqYy9xM2J7mSgXxQx8v0h4w"

management:
  endpoints:
    web:
      exposure:
        include: health,info

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000}

    mail:
    from: ${MAIL_FROM:${MAIL_USER}}

  bootstrap:
    enabled: true
    admin:
      email: "adiministrador@gmail.com"
      name: "Admin do Sistema"
      password: "SenhaFort3$17896"
